import ast
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)

def test_remediations_are_syntactically_valid():
    """
    Ensure ast.parse successfully parses remediations generated by all valid rules.
    """
    scenarios = [
        # SQL Injection
        'def get_user(user_id):\n    query = "SELECT * FROM users WHERE id = " + user_id\n    return db.execute(query)',
        # Hardcoded secret
        'def connect_api():\n    API_KEY = "abc123secret"\n    return connect(API_KEY)',
        # Unsafe shell
        'import subprocess\n\ndef cleanup_temp(path):\n    subprocess.run("rm -rf " + path, shell=True)'
    ]

    for code in scenarios:
        payload = {
            "code": code,
            "language": "python",
            "simulate_non_determinism": False
        }
        response = client.post("/api/scan", json=payload)
        assert response.status_code == 200
        data = response.json()
        assert data["gate_decision"] == "ALLOW"

        remediated_code = data["remediated_code"]
        assert remediated_code is not None
        ast.parse(remediated_code)

def test_sql_remediation_semantic_execution():
    """
    Verify get_user remediation uses placeholder, passes params, and db.execute receives both.
    """
    code = 'def get_user(user_id):\n    query = "SELECT * FROM users WHERE id = " + user_id\n    return db.execute(query)'
    payload = {
        "code": code,
        "language": "python",
        "simulate_non_determinism": False
    }
    response = client.post("/api/scan", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["gate_decision"] == "ALLOW"

    remediated = data["remediated_code"]

    class FakeDB:
        def __init__(self):
            self.called = False
            self.called_query = None
            self.called_params = None

        def execute(self, query, params=None):
            self.called = True
            self.called_query = query
            self.called_params = params
            return "executed_result"

    fake_db = FakeDB()
    local_ns = {"db": fake_db}

    exec(remediated, local_ns)

    get_user_fn = local_ns.get("get_user")
    assert get_user_fn is not None

    result = get_user_fn("test_user_id")
    assert result == "executed_result"
    assert fake_db.called is True
    assert fake_db.called_query == "SELECT * FROM users WHERE id = ?"
    assert fake_db.called_params == ("test_user_id",)

def test_incomplete_template_application_fails_closed():
    """
    Verify that if a required replacement or postcondition fails, the template
    engine returns None, failing closed to REVIEW / NO_TEMPLATE rather than returning partially patched code.
    """
    # SQL query concatenation present but execute call is missing -> zero match on follow-up replacement
    code = 'query = "SELECT * FROM users WHERE id = " + user_id'
    payload = {
        "code": code,
        "language": "python",
        "simulate_non_determinism": False
    }
    response = client.post("/api/scan", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["gate_decision"] == "REVIEW"
    assert data["reason_code"] == "NO_TEMPLATE"
    assert data["remediated_code"] is None

def test_generalized_inputs():
    """
    Verify template engine correctly handles generalized inputs (different tables, field names, and variable names).
    """
    # 1. SQL with different table, field, and variable name
    sql_code = 'def lookup_record(uid):\n    query = "SELECT * FROM items WHERE sku = " + uid\n    return db.execute(query)'
    res = client.post("/api/scan", json={"code": sql_code, "language": "python", "simulate_non_determinism": False})
    assert res.status_code == 200
    data = res.json()
    assert data["gate_decision"] == "ALLOW"
    ast.parse(data["remediated_code"])
    assert 'query = "SELECT * FROM items WHERE sku = ?"' in data["remediated_code"]
    assert 'params = (uid,)' in data["remediated_code"]
    assert 'db.execute(query, params)' in data["remediated_code"]

    # 2. Secret with different key name / value
    secret_code = 'def start_auth():\n    AWS_KEY = "secret_access_key_12345"\n    return init_session(AWS_KEY)'
    res = client.post("/api/scan", json={"code": secret_code, "language": "python", "simulate_non_determinism": False})
    assert res.status_code == 200
    data = res.json()
    assert data["gate_decision"] == "ALLOW"
    ast.parse(data["remediated_code"])
    assert 'AWS_KEY = os.getenv("AWS_KEY")' in data["remediated_code"]

    # 3. Shell with different command and argument variable
    shell_code = 'import subprocess\n\ndef list_dir(folder):\n    subprocess.run("ls -la " + folder, shell=True)'
    res = client.post("/api/scan", json={"code": shell_code, "language": "python", "simulate_non_determinism": False})
    assert res.status_code == 200
    data = res.json()
    assert data["gate_decision"] == "ALLOW"
    ast.parse(data["remediated_code"])
    assert 'subprocess.run(["ls", "-la", folder], shell=False)' in data["remediated_code"]

def test_multiple_primary_matches_fail_closed():
    """
    Verify that if a code block contains two primary matches, the engine fails closed (expected match count is 1).
    """
    # Two secret assignments in the same file
    code = 'def double_secret():\n    API_KEY = "abc123secret"\n    DB_KEY = "def456secret"\n    return API_KEY, DB_KEY'
    res = client.post("/api/scan", json={"code": code, "language": "python", "simulate_non_determinism": False})
    assert res.status_code == 200
    data = res.json()
    assert data["gate_decision"] == "REVIEW"
    assert data["reason_code"] == "NO_TEMPLATE"
    assert data["remediated_code"] is None

def test_multiple_follow_up_matches_fail_closed():
    """
    Verify that if a code block contains two follow-up matches, the engine fails closed (expected follow-up count is 1).
    """
    # Two db.execute calls in the same file
    code = 'def double_sql(user_id):\n    query = "SELECT * FROM users WHERE id = " + user_id\n    db.execute(query)\n    return db.execute(query)'
    res = client.post("/api/scan", json={"code": code, "language": "python", "simulate_non_determinism": False})
    assert res.status_code == 200
    data = res.json()
    assert data["gate_decision"] == "REVIEW"
    assert data["reason_code"] == "NO_TEMPLATE"
    assert data["remediated_code"] is None
